import { Edit3, ImageOff, Plus, Search, ShoppingBag, Trash2, UserRound } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import Navbar from '../components/Navbar'
import PageHeader from '../components/PageHeader'
import Modal from '../components/Modal'
import { EmptyState, ErrorBanner, Loading } from '../components/Feedback'
import api, { errorMessage } from '../services/api'

const blank = { title: '', description: '', price: '', imageUrl: '', isAvailable: true }

export default function Marketplace() {
  const user = JSON.parse(localStorage.getItem('campus_user') || '{}')
  const [items, setItems] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState('')
  const [query, setQuery] = useState(''), [modal, setModal] = useState(null), [form, setForm] = useState(blank), [saving, setSaving] = useState(false)
  const load = async () => { setLoading(true); setError(''); try { setItems((await api.get('/products')).data) } catch (e) { setError(errorMessage(e, 'Could not load the marketplace. Make sure the backend is running.')) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const shown = useMemo(() => items.filter(i => `${i.title} ${i.description} ${i.sellerName}`.toLowerCase().includes(query.toLowerCase())), [items, query])
  const openCreate = () => { setForm(blank); setModal('create') }
  const openEdit = (item) => { setForm({ title: item.title, description: item.description || '', price: item.price, imageUrl: item.imageUrl || '', isAvailable: item.isAvailable }); setModal(item) }
  const submit = async (e) => { e.preventDefault(); setSaving(true); setError(''); try { modal === 'create' ? await api.post('/products', { ...form, price: Number(form.price) }) : await api.put(`/products/${modal.id}`, { ...form, price: Number(form.price) }); setModal(null); await load() } catch (err) { setError(errorMessage(err, 'Could not save this listing.')); setModal(null) } finally { setSaving(false) } }
  const remove = async (item) => { if (!window.confirm(`Delete “${item.title}”? This cannot be undone.`)) return; try { await api.delete(`/products/${item.id}`); setItems(items.filter(i => i.id !== item.id)) } catch (e) { setError(errorMessage(e, 'Could not delete this listing.')) } }
  return <><Navbar /><main className="mx-auto max-w-7xl px-5 py-10 lg:px-8 lg:py-14"><PageHeader eyebrow="Campus marketplace" title="Good finds, close by" description="Buy and sell within your trusted campus community. No shipping, no strangers—just students helping students." action={<button onClick={openCreate} className="primary-btn"><Plus size={18} />List an item</button>} />
    <ErrorBanner message={error} />
    <div className="mb-8 flex max-w-xl items-center gap-3 rounded-full border border-ink/10 bg-white px-5 shadow-sm"><Search className="text-moss" size={19} /><input className="w-full bg-transparent py-3.5 text-sm outline-none" placeholder="Search campus listings…" value={query} onChange={e => setQuery(e.target.value)} /></div>
    {loading ? <Loading /> : shown.length ? <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{shown.map((item, index) => { const mine = item.sellerEmail === user.email; return <article key={item.id} className="card overflow-hidden"><div className={`relative aspect-[4/3] overflow-hidden ${['bg-[#cde6d8]','bg-[#f7d6a8]','bg-[#cbdff1]','bg-[#e5d2ef]'][index % 4]}`}>{item.imageUrl ? <img src={item.imageUrl} alt="" className="h-full w-full object-cover" onError={e => e.currentTarget.style.display = 'none'} /> : <ImageOff className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 text-ink/20" size={42} />}{mine && <span className="absolute left-3 top-3 rounded-full bg-pine px-3 py-1 text-[10px] font-extrabold uppercase tracking-wider text-white">Your listing</span>}</div><div className="p-5"><div className="flex items-start justify-between gap-3"><h2 className="font-display text-lg font-semibold leading-tight">{item.title}</h2><p className="shrink-0 font-display text-lg font-bold text-moss">₹{Number(item.price).toLocaleString('en-IN')}</p></div><p className="mt-2 line-clamp-2 min-h-10 text-xs leading-5 text-ink/50">{item.description || 'No description provided.'}</p><div className="mt-5 flex items-center justify-between border-t border-ink/5 pt-4"><span className="flex min-w-0 items-center gap-1.5 truncate text-xs font-bold text-ink/50"><UserRound size={14} />{item.sellerName}</span>{mine ? <span className="flex gap-1"><button aria-label="Edit listing" onClick={() => openEdit(item)} className="grid h-8 w-8 place-items-center rounded-full bg-mint text-moss hover:bg-pine hover:text-white"><Edit3 size={14} /></button><button aria-label="Delete listing" onClick={() => remove(item)} className="grid h-8 w-8 place-items-center rounded-full bg-red-50 text-red-600 hover:bg-red-600 hover:text-white"><Trash2 size={14} /></button></span> : <button className="text-xs font-extrabold text-moss hover:underline">Message</button>}</div></div></article>})}</div> : <EmptyState icon={ShoppingBag} title="Nothing listed yet" text={query ? 'No listings match your search.' : 'Be the first student to put something useful back into circulation.'} action={!query && <button onClick={openCreate} className="primary-btn"><Plus size={17} />List an item</button>} />}
  </main>{modal && <Modal title={modal === 'create' ? 'List an item' : 'Edit your listing'} subtitle="Clear details help campus buyers decide faster." onClose={() => setModal(null)}><form onSubmit={submit} className="space-y-4"><div><label className="label">Item title</label><input className="field" placeholder="e.g. Engineering drawing kit" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} required /></div><div><label className="label">Description</label><textarea className="field min-h-24 resize-none" placeholder="Condition, pickup location, and anything helpful…" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></div><div className="grid gap-4 sm:grid-cols-2"><div><label className="label">Price (₹)</label><input className="field" type="number" min="0" step="0.01" value={form.price} onChange={e => setForm({ ...form, price: e.target.value })} required /></div><div><label className="label">Image URL</label><input className="field" type="url" placeholder="https://…" value={form.imageUrl} onChange={e => setForm({ ...form, imageUrl: e.target.value })} /></div></div><label className="flex items-center gap-3 rounded-2xl bg-white p-4 text-sm font-bold"><input type="checkbox" checked={form.isAvailable} onChange={e => setForm({ ...form, isAvailable: e.target.checked })} className="h-4 w-4 accent-[#1c5c53]" />Available for sale</label><div className="flex justify-end gap-3 pt-2"><button type="button" className="secondary-btn" onClick={() => setModal(null)}>Cancel</button><button className="primary-btn" disabled={saving}>{saving ? 'Saving…' : 'Save listing'}</button></div></form></Modal>}</>
}
